Repository codeforboston/cliff-effects, pull requests merged in 2018-07, with the labels that each got.

#614 Localization current expenses
  src/localization/en.js
Labels: infrastructure

#619 Fixes #450 Makes sub-section for income earned because of care
  src/forms/CashFlowRowAfterConfirm.js
  src/forms/CurrentExpenses.js
  src/forms/formHelpers.js
  src/index.css
  src/utils/cashflow.js
Labels: feature

#621 make top left nav home to app; move CfB logo closes #542
  src/components/Footer.js
  src/components/MainMenu.js
Labels: feature

#632 Add Code coverage command
  .travis.yml
  README.md
  package.json
Labels: testing

#640 change submit button in FeebackFrom to teal
  src/components/prompts/FeedbackForm.js
Labels: feature

#637 Localization implementation #500 - Household.js and en.js
  src/forms/Household.js
  src/localization/en.js
Labels: infrastructure

#638 Localization CurrentExpenses.js issue #500
  src/forms/CurrentExpenses.js
  src/localization/en.js
Labels: infrastructure

#647 Fixes #646 - reduce form section bottom nav buttons to one instantiation.
  src/containers/VisitPage.js
  src/forms/CurrentBenefits.js
  src/forms/CurrentExpenses.js
  src/forms/CurrentIncome.js
  src/forms/Household.js
  src/forms/Predictions.js
  src/forms/formHelpers.js
  src/localization/en.js
  src/test/forms/__snapshots__/Predictions.test.js.snap
Labels: feature, infrastructure

#645 Adds `lang` code during interpolation. Fixes #644.
  src/App.js
  src/containers/VisitPage.js
  src/utils/interpolation.js
Labels: feature

#623 ManagedNumberField cleaning up variable name and function call
  src/forms/formHelpers.js
  src/test/forms/ManagedNumberField.test.js
  src/test/forms/__snapshots__/CashFlowRow.test.js.snap
Labels: infrastructure

#643 Upates linting from recent PRs
  src/components/Footer.js
Labels: infrastructure

#650 Localization 3rd try CurrentIncome.js for issue #500
  src/forms/CurrentIncome.js
Labels: infrastructure

#654 Fixes #641 fixing typo in About page.
  src/localization/en.js
Labels: bug

#651 Snippets to backticks instead of quotes
  src/localization/de.js
  src/localization/en.js
  src/localization/es.js
  src/localization/zh.js
Labels: infrastructure

#663 Parker/issue #542 remove checkmarks
  src/components/StepBar.js
Labels: feature

#664 Install node dependencies
  .travis.yml
  package.json
Labels: bug, infrastructure

#658 Fixes interpolation not giving keys because of my last fix
  src/utils/interpolation.js
Labels: bug, infrastructure

#675 Some cleanup, including stuff I don't see us using anymore - #670
  src/forms/formHelpers.js
Labels: infrastructure

#672 Interactive UI elements moved to own file - #670
  src/forms/CashFlowRowAfterConfirm.js
  src/forms/CurrentBenefits.js
  src/forms/CurrentExpenses.js
  src/forms/Household.js
  src/forms/formHelpers.js
  src/forms/inputs.js
  src/index.css
  src/test/forms/ManagedNumberField.test.js
Labels: infrastructure

#671 Moves headings to their own file - issue #670
  src/components/headings.js
  src/forms/CurrentExpenses.js
  src/forms/CurrentIncome.js
  src/forms/Household.js
  src/forms/Predictions.js
  src/forms/formHelpers.js
Labels: infrastructure

#677 Fixes no langCode as nested snippets are interpolated
  src/utils/interpolation.js
Labels: bug, infrastructure

#679 Fix language codes not actually specific to snippets
  src/App.js
  src/utils/getTextForLanguage.js
  src/utils/interpolation.js
Labels: bug, discussion needed, infrastructure
