Repository codeforboston/cliff-effects, pull requests merged in 2018-03, with the labels that each got.

#430 Fixes #429, voucher rent expenses language
  src/forms/rentFields.js
Labels: feature

#433 Fixes #431, Rent fields to only monthly values
  src/forms/CurrentExpenses.js
  src/forms/formHelpers.js
  src/forms/rentFields.js
Labels: discussion needed, feature, infrastructure

#443 Fix errors when editing age field
  src/forms/Household.js
Labels: bug

#449 Adds Fixed Reset Button (Issue #427)
  src/components/ResetAnytime.js
  src/containers/VisitPage.js
  src/index.css
Labels: feature

#442 Fixes #441, explanation of SNAP being calculated
  src/forms/CurrentIncome.js
Labels: feature
