Repository codeforboston/cliff-effects, pull requests merged in 2018-06, with the labels that each got.

#568 Makes changes for lint msgs issue #507 - FeedbackPrompt.js
  src/components/FeedbackPrompt.js
Labels: infrastructure

#574 Deleted file masshealth_old.js for lint msgs issue #507
  src/programs/massachusetts/masshealth_old.js
Labels: infrastructure

#575 Makes changes for lint msgs issue #507 - samples.test.js
  src/test/programs/federal/snap/samples.test.js
Labels: infrastructure

#578 Makes changes for lint msgs issue #507 - AREA_MEDIAN_INCOME_LIMITS_MA…
  src/data/massachusetts/2017/AREA_MEDIAN_INCOME_LIMITS_MA_2017.js
Labels: infrastructure

#561 Unit tests for ManagedNumberField for handleFocus and handleBlur
  src/test/forms/__snapshots__/formHelpers.test.js.snap
  src/test/forms/formHelpers.test.js
Labels: testing

#579 Issue #507 - clears lint warnings for 'src/forms/Predictions.js'
  src/forms/Predictions.js
Labels: infrastructure

#580 Issue #507 - clears lint warnings for snap 'unit.test.js'
  src/test/programs/federal/snap/unit.test.js
Labels: infrastructure

#582 Separates tests for renter, adds test for no utilities
  src/test/programs/federal/snap/unit.test.js
Labels: testing

#588 Makes changes for lint msgs issue #507 - generateTestCases.js
  src/test/programs/federal/snap/generateTestCases.js
Labels: discussion needed

#557 Adds labels in German for About Page
  src/localization/de.js
Labels: infrastructure

#594 Makes changes for lint msgs issue #507 - formHelpers.js
  src/forms/formHelpers.js
Labels: infrastructure

#592 Makes changes for lint msgs issue #507 - getGovData.test.js
  src/test/utils/getGovData.test.js
Labels: infrastructure

#598 Fixes #595 - graphs don't match each other
  src/forms/ResultsGraph.js
Labels: bug

#599 Changes array element new-line rules. #507.
  .eslintrc.json
  src/components/AboutContent.js
  src/data/massachusetts/name-cores.js
  src/forms/Household.js
  src/forms/Predictions.js
  src/forms/ResultsGraph.js
  src/localization/de.js
  src/localization/en.js
  src/test/programs/federal/snap/generateTestCases.js
  src/test/programs/federal/snap/regression.test.js
  src/test/programs/federal/snap/unit.test.js
  src/test/utils/getMembers.test.js
  src/test/utils/valueFixers.test.js
Labels: infrastructure

#600 Localization for "Household" section
  src/localization/en.js
Labels: infrastructure

#603 Fixes #550 - Updates for buttons and last reset button
  src/forms/Predictions.js
  src/index.css
  src/test/forms/__snapshots__/Predictions.test.js.snap
Labels: feature

#602 Move graphs into output folder (PR 2)
  src/forms/Predictions.js
  src/forms/output/BenefitsTable.js
  src/forms/output/ResultsGraph.js
  src/test/forms/BenefitsTable.test.js
Labels: infrastructure

#604 Refactors graph functionality (PR 3)
  src/forms/output/ResultsGraph.js
  src/forms/output/StackedBarGraph.js
  src/forms/output/VerticalLine.js
  src/utils/charts/PROGRAM_CHART_VALUES.js
  src/utils/charts/chartFormatting.js
  src/utils/charts/getChartData.js
  src/utils/convert-by-timescale.js
Labels: infrastructure

#605 Splits stacked area graph from graphs file
  src/forms/Predictions.js
  src/forms/output/ResultsGraph.js
  src/forms/output/StackedAreaGraph.js
Labels: infrastructure

#606 Split benefits graph from the main graphs file (PR 5)
  src/forms/Predictions.js
  src/forms/output/BenefitsLineGraph.js
  src/forms/output/ResultsGraph.js
Labels: infrastructure

#607 Fixes #587 - Add CashFlowRow tests & fix math errors
  src/forms/CurrentIncome.js
  src/forms/formHelpers.js
  src/test/forms/CashFlowRow.test.js
  src/test/forms/ManagedNumberField.test.js
  src/test/forms/__snapshots__/CashFlowRow.test.js.snap
  src/test/forms/__snapshots__/ManagedNumberField.test.js.snap
  src/utils/math.js
Labels: testing

#608 Removes outdated, renames to 'GraphHolder' (PR 6)
  src/forms/Predictions.js
  src/forms/output/GraphHolder.js
Labels: infrastructure

#609 Move prompts into folder and new, traceable, history subverting (PR 1)
  src/App.js
  src/components/prompts/ConfirmLeave.js
  src/components/prompts/ErrorPrompt.js
  src/components/prompts/FeedbackAnytime.js
  src/components/prompts/FeedbackPrompt.js
  src/components/prompts/OnLeavePrompt.js
  src/components/prompts/ReactRouterConfirmLeave.js
  src/components/prompts/ResetAnytime.js
  src/containers/VisitPage.js
  src/utils/getUserConfirmation.js
Labels: infrastructure

#610 Small prompt shifts. Changing some names, etc. (PR 2)
  src/components/prompts/ErrorPrompt.js
  src/components/prompts/FeedbackAnytime.js
  src/components/prompts/FeedbackForm.js
  src/components/prompts/OnLeavePrompt.js
  src/components/prompts/ReactRouterConfirmLeave.js
  src/components/prompts/ResetAnytime.js
  src/containers/VisitPage.js
  src/forms/Predictions.js
Labels: infrastructure

#613 Changes `OnLeavePrompt` to `FeedbackPrompt`
  src/components/prompts/FeedbackPrompt.js
  src/components/prompts/ReactRouterConfirmLeave.js
  src/containers/VisitPage.js
Labels: infrastructure

#618 Allows template literals. Maybe use these instead of quotes?
  .eslintrc.json
Labels: infrastructure

#612 Localization formHelpers and CurrentBenefits
  src/localization/en.js
Labels: infrastructure

#615 More attempts at clarifying prompt related functionality
  src/components/prompts/BrowserLeaveListener.js
  src/components/prompts/ErrorListener.js
  src/components/prompts/ReactRouterLeaveListener.js
  src/components/prompts/ResetAnytime.js
  src/containers/VisitPage.js
  src/utils/getUserConfirmation.js
Labels: infrastructure
