Repository codeforboston/cliff-effects, pull requests merged in 2018-09, with the labels that each got.

#727 localStorage for dev HUD because otherwise it's nuts
  src/App.js
  src/test/App.test.js
Labels: feature

#722 Turns subtle multi-line ternaries into more explicit function call
  src/App.js
  src/components/renderIfTrue.js
  src/test/components/renderIfTrue.test.js
Labels: infrastructure

#735 Gets rid of old files, fixes a file location and a name
  src/config/dummyClients.js
  src/data/massachusetts/2017/AREA_MEDIAN_INCOME_LIMITS_MA_2017.js
  src/data/massachusetts/2018/FMRS_MA_2018.js
  src/forms/CashFlowRowAfterConfirm.js
  src/programs/massachusetts/template.js
  src/test/components/prompts/FeedbackPrompt.test.js
  src/test/components/prompts/__snapshots__/FeedbackPrompt.test.js.snap
  src/test/forms/CashFlowInputsRow.test.js
  src/test/forms/__snapshots__/CashFlowInputsRow.test.js.snap
  src/utils/getTimeSetter.js
Labels: infrastructure

#728 Surrounder - the layout super-component
  src/components/Surrounder.js
  src/components/details.js
  src/forms/CurrentBenefits.js
  src/forms/CurrentExpenses.js
  src/forms/ShowOnYes.js
  src/index.css
Labels: infrastructure

#740 Fixes styling for footer link, adds flexibility to `ExternalLink`
  src/forms/formHelpers.js
  src/index.css
  src/localization/inlineComponents.js
  src/utils/interpolation.js
Labels: infrastructure

#737 Update expenses to dev
  .eslintrc.json
  src/App.js
  src/components/CustomClient.js
  src/components/Surrounder.js
  src/components/details.js
  src/components/dev/DevHud.js
  src/components/prompts/FeedbackForm.js
  src/components/renderIfTrue.js
  src/config/dummyClients.js
  src/containers/DevSwitch.js
  src/containers/VisitPage.js
  src/data/massachusetts/2017/AREA_MEDIAN_INCOME_LIMITS_MA_2017.js
  src/data/massachusetts/2018/FMRS_MA_2018.js
  src/forms/CashFlowRowAfterConfirm.js
  src/forms/CurrentBenefits.js
  src/forms/CurrentExpenses.js
  src/forms/ExpensesOther.js
  src/forms/FormPartsContainer.js
  src/forms/Household.js
  src/forms/Predictions.js
  src/forms/ShowOnYes.js
  src/forms/inputs.js
  src/forms/output/BenefitsTable.js
  src/index.css
  src/index.js
  src/localization/de.js
  src/localization/en.js
  src/localization/es.js
  src/localization/inlineComponents.js
  src/localization/zh.js
  src/programs/massachusetts/template.js
  src/styles/dev.css
  src/test/App.test.js
  src/test/components/prompts/FeedbackPrompt.test.js
  src/test/components/prompts/__snapshots__/FeedbackPrompt.test.js.snap
  src/test/components/renderIfTrue.test.js
  src/test/forms/CashFlowInputsRow.test.js
  src/test/forms/__snapshots__/CashFlowInputsRow.test.js.snap
  src/test/forms/__snapshots__/Predictions.test.js.snap
  src/test/programs/federal/snap/generateTestCases.js
  src/utils/getSideEffects.js
  src/utils/getTimeSetter.js
  src/utils/interpolation.js
  src/utils/setNestedProperty.js
Labels: infrastructure

#739 Fixes big oversight in benefit calculations
  src/forms/output/BenefitsTable.js
  src/forms/output/StackedBarGraph.js
  src/utils/charts/getChartData.js
Labels: bug

#746 Make docs work by putting app on cliff-effects/app, docs on cliff-effects/docs
  package-lock.json
  package.json
  postbuild.js
  redirect.html
  src/App.js
  src/forms/CurrentExpenses.js
  src/forms/inputs.js
Labels: bug, infrastructure

#750 Asks user for permission to save their data before sending it - fixes #744
  src/components/prompts/FeedbackForm.js
Labels: feature

#749 [WIP] Refactored HomePage.js inline styles - #288
  README.md
  src/containers/HomePage.js
  src/index.css
Labels: infrastructure

#745 [WIP] initial checks for localization reports #527
  src/test/localization/WIP_all.test.js
Labels: discussion needed, infrastructure

#760 Update Chinese localization
  src/localization/zh.js
Labels: non-code

#766 Fix StackedAreaGraph not adjusting to future income and not redrawing
  src/forms/output/StackedAreaGraph.js
Labels: bug

#773 Updates linting
  src/containers/HomePage.js
  src/forms/cashflow.js
  src/localization/zh.js
Labels: infrastructure

#743 Clarifies `updateClientValue` flow - #585
  src/containers/VisitPage.js
  src/forms/CurrentBenefits.js
  src/forms/CurrentExpenses.js
  src/forms/ShowOnYes.js
  src/forms/inputs.js
  src/utils/convertForUpdate.js
  src/utils/setNestedProperty.js
Labels: infrastructure

#775 Put redirect files into dir and copy them all after building
  postbuild.js
  redirect/index.html
  redirect/redirect.css
Labels: infrastructure

#772 Updates to match with wiki changes
  README.md
Labels: infrastructure

#779 Removes last minor version numbers from en.js
  src/containers/VisitPage.js
  src/localization/en.js
Labels: infrastructure

#774 Localization report util function tests and jsdocs - #527
  src/test/utils/objectKeyPaths.test.js
  src/utils/objectKeyPaths.js
Labels: infrastructure

#781 Redirect fix
  redirect/index.html
Labels: bug

#777 Fixed redirect.html - fixes #776
  redirect.html
Labels: bug

#782 Converts to new snippets specs - fixes #778
  src/components/AboutContent.js
  src/components/Footer.js
  src/components/StepBar.js
  src/containers/VisitPage.js
  src/forms/CurrentBenefits.js
  src/forms/CurrentExpenses.js
  src/forms/CurrentIncome.js
  src/forms/Household.js
  src/forms/Predictions.js
  src/forms/output/BenefitsTable.js
  src/localization/en.js
  src/test/forms/BenefitsTable.test.js
  src/test/forms/CurrentBenefits.test.js
  src/test/forms/CurrentExpenses.test.js
  src/test/forms/CurrentIncome.test.js
  src/test/forms/Household.test.js
  src/test/forms/Predictions.test.js
  src/test/forms/__snapshots__/BenefitsTable.test.js.snap
  src/test/forms/__snapshots__/CurrentBenefits.test.js.snap
  src/test/forms/__snapshots__/CurrentExpenses.test.js.snap
  src/test/forms/__snapshots__/CurrentIncome.test.js.snap
  src/test/forms/__snapshots__/Household.test.js.snap
  src/test/forms/__snapshots__/Predictions.test.js.snap
  src/utils/interpolation.js
Labels: infrastructure

#786 Updates linting
  src/components/Header.js
  src/containers/HomePage.js
Labels: infrastructure

#785 Abstract calcs - #784
  src/forms/output/BenefitsLineGraph.js
  src/forms/output/BenefitsTable.js
  src/forms/output/StackedAreaGraph.js
  src/forms/output/StackedBarGraph.js
  src/programs/applyAndPushBenefits.js
  src/utils/charts/getChartData.js
Labels: infrastructure

#783 Inline style Refactoring
  src/components/AboutContent.js
  src/components/Header.js
  src/components/PageLayout.js
  src/index.css
Labels: infrastructure

#768 Increase timeout for Jest on big regression test
  src/test/programs/federal/snap/regression.test.js
Labels: bug, infrastructure

#741 Adds snippets for tables/charts/graphs in Predictions section of en.js
  src/localization/en.js
  src/test/forms/__snapshots__/Predictions.test.js.snap
Labels: infrastructure

#798 updates child support text fixes #762
  src/forms/CurrentExpenses.js
  src/localization/en.js
  src/test/forms/__snapshots__/CurrentExpenses.test.js.snap
  src/test/forms/__snapshots__/Predictions.test.js.snap
Labels: feature

#801 Thanks! But reverting "updates child support text fixes #762" pending passing tests, etc.
  src/forms/CurrentExpenses.js
  src/localization/en.js
  src/test/forms/__snapshots__/CurrentExpenses.test.js.snap
  src/test/forms/__snapshots__/Predictions.test.js.snap
Labels: feature, infrastructure

#803 Lints
  src/components/AboutContent.js
  src/components/PageLayout.js
  src/localization/contributors.js
Labels: infrastructure

#804 Switches to `beforeMoney` and `afterMoney`, as discussed
  src/forms/output/BenefitsTable.js
  src/localization/en.js
  src/localization/zh.js
  src/test/forms/__snapshots__/Predictions.test.js.snap
Labels: infrastructure

#805 Vietnamese translation - #513, #500
  src/localization/all.js
  src/localization/contributors.js
  src/localization/vi.js
Labels: feature
