Repository codeforboston/cliff-effects, pull requests merged in 2018-05, with the labels that each got.

#484 fixes #477 switchedRadioLabelYesNo
  src/forms/CurrentExpenses.js
  src/forms/formHelpers.js
  src/index.css
Labels: feature

#489 Fixes #488 - Sets up initial localization structure
  src/containers/VisitPage.js
  src/forms/CurrentBenefits.js
  src/index.js
  src/localization/all.js
  src/localization/en.js
  src/utils/getTranslate.js
Labels: infrastructure

#498 Fixes `hasHousing` to `hasSection8` to be more accurate
  src/containers/VisitPage.js
  src/forms/BenefitsTable.js
  src/forms/CurrentBenefits.js
  src/forms/Predictions.js
  src/forms/ResultsGraph.js
  src/localization/en.js
  src/test/forms/__snapshots__/Predictions.test.js.snap
  src/test/sampleClients.js
  src/utils/CLIENT_DEFAULTS.js
  src/utils/valueFixers.js
Labels: infrastructure

#499 Small cleanup for client defaults and corresponding snapshot
  src/test/forms/__snapshots__/Predictions.test.js.snap
  src/utils/CLIENT_DEFAULTS.js
Labels: infrastructure

#503 Attempts more readable way of getting limits with gov data
  src/programs/federal/snap.js
  src/test/programs/federal/snap/unit.test.js
  src/test/utils/getGovData.test.js
  src/utils/convert-by-timescale.js
  src/utils/getGovData.js
  src/utils/math.js
Labels: infrastructure

#504 Adds graphs back into the app, but in a way that's more opt-in
  src/forms/Predictions.js
  src/forms/ResultsGraph.js
  src/index.css
  src/programs/federal/snap.js
  src/test/forms/__snapshots__/Predictions.test.js.snap
Labels: feature

#509 Linter warning fixes for a couple of files, #507
  src/forms/BenefitsTable.js
  src/forms/CashFlowRowAfterConfirm.js
  src/forms/CurrentBenefits.js
  src/forms/Predictions.js
Labels: infrastructure

#517 Makes changes for lint warnings issue #507 -getUserConfirmation.js
  src/utils/getUserConfirmation.js
Labels: infrastructure

#518 Removes jsdocs linting until that package is more consistent. Issue #507
  .eslintrc.json
Labels: infrastructure

#515 Runs lint fix on newly merged code
  src/localization/en.js
Labels: infrastructure

#514 changed rotation for vert buttons to fix alignment
  src/index.css
Labels: feature

#516 Curly bracket linting rules
  .eslintrc.json
  src/App.js
  src/components/BetaWarning.js
  src/components/CustomClient.js
  src/components/FeedbackAnytime.js
  src/components/FeedbackPrompt.js
  src/components/Footer.js
  src/components/GraphTimeButtons.js
  src/components/MainMenu.js
  src/components/OnLeavePrompt.js
  src/components/PageLayout.js
  src/components/ReactRouterConfirmLeave.js
  src/components/ResetAnytime.js
  src/components/StepBar.js
  src/containers/VisitPage.js
  src/forms/BenefitsTable.js
  src/forms/CashFlowRowAfterConfirm.js
  src/forms/CurrentExpenses.js
  src/forms/CurrentIncome.js
  src/forms/Household.js
  src/forms/Predictions.js
  src/forms/ResultsGraph.js
  src/forms/formHelpers.js
  src/forms/rentFields.js
  src/test/forms/BenefitsTable.test.js
  src/test/forms/Predictions.test.js
  src/test/utils/getMembers.test.js
Labels: infrastructure

#520 Fixes #511 - Graph timescales labels don't update with user change
  src/forms/ResultsGraph.js
Labels: bug, discussion needed

#523 Lint config to add line at end of file
  .eslintrc.json
  src/components/Footer.js
  src/components/Header.js
  src/components/StepBar.js
  src/config/dummyClients.js
  src/setupTests.js
  src/test/App.test.js
  src/test/forms/BenefitsTable.test.js
  src/test/forms/Predictions.test.js
Labels: infrastructure

#524 eslint config format
  .eslintrc.json
Labels: infrastructure

#522 Experiments in plainer language.
  src/forms/Predictions.js
  src/test/forms/__snapshots__/Predictions.test.js.snap
Labels: feature

#528 Moves `snippets` to top level of app.
  src/App.js
  src/containers/VisitPage.js
Labels: infrastructure

#530 Adjusts snippets for incomes to match current income labels
  src/localization/en.js
Labels: feature

#531 Adds localization data for Home Page
  src/localization/en.js
Labels: infrastructure
