Repository codeforboston/cliff-effects, pull requests merged in 2018-08, with the labels that each got.

#685 Update Chinese localization - #500
  src/localization/zh.js
Labels: feature

#688 Add me as a contributor
  src/localization/contributors.js
Labels: feature

#681 Cache interpolated/merged snippets
  src/App.js
  src/utils/getTextForLanguage.js
Labels: discussion needed, infrastructure

#684 Gets rid of `getTimeSetter` for clarity and more consistent naming - #585
  src/containers/VisitPage.js
  src/forms/CashFlowRowAfterConfirm.js
  src/forms/CurrentBenefits.js
  src/forms/CurrentExpenses.js
  src/forms/CurrentIncome.js
  src/forms/Household.js
  src/forms/Predictions.js
  src/forms/cashflow.js
  src/forms/inputs.js
  src/forms/rentFields.js
  src/test/forms/CashFlowRow.test.js
  src/test/forms/CurrentBenefits.test.js
  src/test/forms/CurrentExpenses.test.js
  src/test/forms/CurrentIncome.test.js
  src/test/forms/Household.test.js
  src/test/forms/Predictions.test.js
  src/test/forms/__snapshots__/CurrentBenefits.test.js.snap
  src/test/forms/__snapshots__/CurrentExpenses.test.js.snap
  src/test/forms/__snapshots__/CurrentIncome.test.js.snap
  src/test/forms/__snapshots__/Household.test.js.snap
  src/test/forms/__snapshots__/Predictions.test.js.snap
  src/test/utils/getTimeSetter.test.js
Labels: infrastructure

#694 Fixes linting that has fallen by the wayside
  src/containers/VisitPage.js
  src/forms/CurrentBenefits.js
  src/forms/CurrentExpenses.js
  src/forms/CurrentIncome.js
  src/forms/Household.js
  src/localization/zh.js
  src/test/FeedbackPrompt.test.js
Labels: infrastructure

#692 Adds and implements expandable details - fixes #691
  src/components/details.js
  src/forms/CurrentExpenses.js
  src/index.css
Labels: feature

#700 Adds text snippets for Predictions.js to en.js
  src/localization/en.js
Labels: infrastructure

#704 removes Travis caching
  .travis.yml
Labels: infrastructure

#705 Update English localization in about section to latest value in Google Docs
  src/localization/en.js
Labels: feature

#703 Switches to current convention for export
  src/forms/CurrentBenefits.js
  src/forms/CurrentExpenses.js
  src/forms/CurrentIncome.js
  src/forms/FormPartsContainer.js
  src/forms/Household.js
  src/forms/Predictions.js
Labels: infrastructure

#695 Offers questions about other expenses to the user for graph visuals - #397
  src/containers/VisitPage.js
  src/data/massachusetts/name-cores.js
  src/forms/CashFlowRowAfterConfirm.js
  src/forms/CurrentExpenses.js
  src/forms/CurrentIncome.js
  src/forms/ExpensesOther.js
  src/forms/Predictions.js
  src/forms/ShowOnYes.js
  src/forms/cashflow.js
  src/forms/inputs.js
  src/index.css
  src/test/forms/CashFlowRow.test.js
  src/test/forms/__snapshots__/CashFlowRow.test.js.snap
  src/test/forms/__snapshots__/CurrentBenefits.test.js.snap
  src/test/forms/__snapshots__/CurrentExpenses.test.js.snap
  src/test/forms/__snapshots__/CurrentIncome.test.js.snap
  src/test/forms/__snapshots__/Household.test.js.snap
  src/test/forms/__snapshots__/ManagedNumberField.test.js.snap
  src/test/forms/__snapshots__/Predictions.test.js.snap
  src/utils/CLIENT_DEFAULTS.js
  src/utils/cashflow.js
  src/utils/valueFixers.js
Labels: feature

#713 restore disclaimer above predictions tables, restore DownloadFile.js …
  README.md
  src/forms/Predictions.js
  src/test/forms/__snapshots__/Predictions.test.js.snap
Labels: feature

#716 Premature feature temporarily hidden to avoid messy revert
  src/forms/CurrentExpenses.js
Labels: bug

#719 Implements dev HUD
  src/App.js
  src/components/CustomClient.js
  src/components/details.js
  src/components/dev/DevHud.js
  src/containers/DevSwitch.js
  src/containers/VisitPage.js
  src/index.css
  src/index.js
  src/styles/dev.css
  src/utils/interpolation.js
Labels: feature

#715 Use snippets in predictions page - Issue #513
  src/forms/Predictions.js
  src/localization/en.js
  src/test/forms/__snapshots__/Predictions.test.js.snap
Labels: infrastructure
