Repository codeforboston/cliff-effects, pull requests merged in 2018-11, with the labels that each got.

#948 Some items in #945, VisitPage resolution/clean-up
  src/containers/VisitPage.js
  src/test/forms/CurrentBenefits.test.js
  src/test/forms/CurrentExpenses.test.js
  src/test/forms/CurrentIncome.test.js
  src/test/forms/Household.test.js
Labels: infrastructure

#950 Change default to display failing checks
  src/components/dev/LocalizationReport.js
Labels: feature

#942 Fixes #941, buttons wrong style
  src/index.css
Labels: bug

#951 Items 3, (4 gone), and 5 of #945, clean/resolve some `VisitPage` stuff
  src/containers/VisitPage.js
Labels: infrastructure

#954 Fixes #9 of #923, switch `income` to `earned` where needed
  src/forms/Predictions.js
  src/forms/output/BenefitsLineGraph.js
  src/forms/output/BenefitsTable.js
  src/forms/output/StackedAreaGraph.js
  src/forms/output/StackedBarGraph.js
  src/forms/output/Summary.js
  src/forms/output/VerticalLine.js
  src/localization/en.js
  src/localization/vi.js
  src/localization/zh.js
  src/programs/applyAndPushBenefits.js
  src/test/forms/output/__snapshots__/BenefitsLineGraph.test.js.snap
  src/test/forms/output/__snapshots__/StackedAreaGraph.test.js.snap
  src/test/forms/output/__snapshots__/StackedBarGraph.test.js.snap
  src/utils/charts/PROGRAM_CHART_VALUES.js
Labels: feature, infrastructure

#960 Fixes #958, invalid input message not going away
  src/forms/cashflow.js
  src/test/forms/cashflow/__snapshots__/CashFlowInputsRow.test.js.snap
Labels: bug

#959 Aria labels for cashflow rows, attempt 1. #816
  src/forms/cashflow.js
  src/forms/formHelpers.js
  src/forms/inputs.js
  src/forms/rentFields.js
  src/test/forms/cashflow/__snapshots__/CashFlowContainer.test.js.snap
  src/test/forms/cashflow/__snapshots__/CashFlowInputsRow.test.js.snap
  src/test/forms/inputs/ManagedNumberField.test.js
  src/test/forms/inputs/__snapshots__/ManagedNumberField.test.js.snap
Labels: feature

#944 Moves 'contants' and renames file/var. Fixes #943
  src/components/StepBar.js
  src/containers/VisitPage.js
  src/forms/STEP_VALS.js
  src/test/components/StepBar.test.js
Labels: infrastructure

#968 Fixes #967, 'Household' section crashing and burning
  src/forms/inputs.js
  src/test/forms/Household.test.js
  src/test/forms/__snapshots__/Household.test.js.snap
Labels: bug

#963 Fixes #945 #6 last item, switch var name
  src/containers/VisitPage.js
  src/forms/STEP_VALS.js
Labels: infrastructure

#971 `shallow` to `mount` in steps, removes snapshots, #966
  src/test/forms/CurrentBenefits.test.js
  src/test/forms/CurrentExpenses.test.js
  src/test/forms/CurrentIncome.test.js
  src/test/forms/__snapshots__/CurrentBenefits.test.js.snap
  src/test/forms/__snapshots__/CurrentExpenses.test.js.snap
  src/test/forms/__snapshots__/CurrentIncome.test.js.snap
Labels: infrastructure, testing

#969 `shallow()` to `mount()` for some tests as much as possible, #966
  src/test/components/ButtonReset.test.js
  src/test/components/prompts/FeedbackPrompt.test.js
  src/test/components/prompts/__snapshots__/FeedbackPrompt.test.js.snap
  src/test/forms/cashflow/CashFlowInputsRow.test.js
  src/test/forms/cashflow/__snapshots__/CashFlowInputsRow.test.js.snap
Labels: infrastructure, testing

#970 A little trouble changing ManagedNumberField `shallow` to `mount` #966
  src/test/forms/inputs/ManagedNumberField.test.js
  src/test/forms/inputs/__snapshots__/ManagedNumberField.test.js.snap
Labels: testing

#962 Fixes #961 - different abstraction for user message, take 1
  src/components/prompts/FeedbackForm.js
  src/forms/cashflow.js
  src/forms/formHelpers.js
  src/index.css
  src/test/forms/cashflow/__snapshots__/CashFlowContainer.test.js.snap
  src/test/forms/cashflow/__snapshots__/CashFlowDisplayRow.test.js.snap
  src/test/forms/folderHelpers/InvalidMessage.test.js
  src/test/forms/folderHelpers/ValidationError.test.js
Labels: discussion needed, infrastructure

#980 Fix styles broken by new messages
  src/forms/cashflow.js
  src/index.css
  src/test/forms/cashflow/__snapshots__/CashFlowContainer.test.js.snap
Labels: bug

#965 Rearrange and split functions in Expenses
  src/forms/CurrentExpenses.js
Labels: infrastructure

#988 Add lint-staged entry to package.json
  package-lock.json
  package.json
Labels: infrastructure

#990 Fixes #989, fixes MA benefit order
  src/programs/massachusetts/benefitOrder.js
Labels: bug

#932 Replace var with let
  .eslintrc.json
  src/App.js
  src/components/StepBar.js
  src/components/details.js
  src/components/dev/DevHud.js
  src/components/headings.js
  src/components/prompts/ErrorListener.js
  src/components/prompts/FeedbackForm.js
  src/components/prompts/FeedbackPrompt.js
  src/components/prompts/ReactRouterLeaveListener.js
  src/containers/DevSwitch.js
  src/containers/VisitPage.js
  src/forms/ButtonReset.js
  src/forms/CurrentExpenses.js
  src/forms/CurrentIncome.js
  src/forms/ExpensesOther.js
  src/forms/FormPartsContainer.js
  src/forms/Household.js
  src/forms/Predictions.js
  src/forms/ShowOnYes.js
  src/forms/cashflow.js
  src/forms/formHelpers.js
  src/forms/inputs.js
  src/forms/output/BenefitsLineGraph.js
  src/forms/output/BenefitsTable.js
  src/forms/output/GraphHolder.js
  src/forms/output/StackedAreaGraph.js
  src/forms/output/StackedBarGraph.js
  src/forms/output/Summary.js
  src/forms/rentFields.js
  src/programs/allBenefitOps.js
  src/programs/allBenefitOrders.js
  src/programs/applyAndPushBenefits.js
  src/programs/federal/snap.js
  src/programs/massachusetts/benefitOps.js
  src/programs/massachusetts/benefitOrder.js
  src/programs/massachusetts/section8.js
  src/test/forms/CurrentBenefits.test.js
  src/test/forms/CurrentExpenses.test.js
  src/test/forms/CurrentIncome.test.js
  src/test/forms/Household.test.js
  src/test/forms/cashflow/CashFlowInputsRow.test.js
  src/test/forms/inputs/ManagedNumberField.test.js
  src/test/programs/federal/snap/unit.test.js
  src/test/setupJSDOM.js
  src/test/utils/getGovData.test.js
  src/test/utils/math.test.js
  src/utils/cashflow.js
  src/utils/charts/chartFormatting.js
  src/utils/charts/getChartData.js
  src/utils/convert-by-timescale.js
  src/utils/convertForUpdate.js
  src/utils/getGovData.js
  src/utils/getMembers.js
  src/utils/getSideEffects.js
  src/utils/interpolation.js
  src/utils/math.js
  src/utils/setNestedProperty.js
Labels: infrastructure

#994 Fixes #940, combine 'About' components
  src/components/AboutContent.js
  src/containers/AboutPage.js
  src/test/components/AboutContent.test.js
Labels: infrastructure

#984 New charts lib for Benefits Lines graph, #956. Feedback welcome
  package-lock.json
  package.json
  src/forms/Predictions.js
  src/forms/output/BenefitsLines.js
  src/forms/output/BenefitsTable.js
  src/forms/output/GraphHolder.js
  src/forms/output/Summary.js
  src/index.css
  src/localization/en.js
  src/localization/vi.js
  src/localization/zh.js
  src/test/forms/output/GraphHolder.test.js
  src/test/forms/output/__snapshots__/GraphHolder.test.js.snap
  src/utils/charts/chartFormatting.js
Labels: discussion needed, feature

#992 Add node version checking script. Fixes #983
  check-node-version.js
  package.json
Labels: infrastructure

#995 Fixes #953, shifts focus of About page, notes on future fixes
  src/localization/en.js
  src/localization/vi.js
  src/localization/zh.js
Labels: feature

#1002 Fast turnaround? Fixes #1001, removes old link, dates info with time of creation.
  src/containers/AboutPage.js
  src/localization/en.js
  src/localization/vi.js
  src/localization/zh.js
Labels: feature

#1006 Fixes #1003, smaller interval for now.
  src/forms/output/BenefitsLines.js
  src/forms/output/StackedResources.js
Labels: feature

#1008 Proportional zooming on graphs. Fixes #1007
  src/forms/output/BenefitsLines.js
  src/forms/output/StackedResources.js
  src/forms/output/zoom.js
  src/index.css
  src/localization/en.js
  src/localization/vi.js
  src/localization/zh.js
Labels: feature

#1015 Rename 'snippets' to 'translations' in a lot of places. #936
  OVERVIEW.md
  src/App.js
  src/components/Footer.js
  src/components/Header.js
  src/components/MainMenu.js
  src/components/StepBar.js
  src/components/dev/DevHud.js
  src/components/prompts/PredictionsWarning.js
  src/containers/AboutPage.js
  src/containers/VisitPage.js
  src/forms/CurrentBenefits.js
  src/forms/CurrentExpenses.js
  src/forms/CurrentIncome.js
  src/forms/Household.js
  src/forms/Predictions.js
  src/forms/output/BenefitsLines.js
  src/forms/output/BenefitsTable.js
  src/forms/output/GraphHolder.js
  src/forms/output/ResourcesColumns.js
  src/forms/output/StackedResources.js
  src/forms/output/Summary.js
  src/forms/output/chartStringTransformers.js
  src/localization/all.js
  src/localization/inlineComponents.js
  src/styles/dev.css
  src/test/components/ButtonReset.test.js
  src/test/components/Footer.test.js
  src/test/components/Header.test.js
  src/test/components/MainMenu.test.js
  src/test/components/StepBar.test.js
  src/test/containers/AboutPage.test.js
  src/test/forms/CurrentBenefits.test.js
  src/test/forms/CurrentExpenses.test.js
  src/test/forms/CurrentIncome.test.js
  src/test/forms/Household.test.js
  src/test/forms/output/BenefitsTable.test.js
  src/test/helpers.js
  src/utils/getTextForLanguage.js
  src/utils/interpolation.js
Labels: infrastructure

#1020 Replace more snippet references. Fixes #1019
  src/components/dev/DevHud.js
  src/localization/all.js
  src/localization/en.js
  src/utils/getTextForLanguage.js
  src/utils/interpolation.js
Labels: infrastructure

#1017 Code style cleaning in '/src/components/dev', #1018
  src/components/dev/DevHud.js
  src/components/dev/LocalizationReport.js
Labels: infrastructure

#996 Updates de.js
  src/localization/de.js
Labels: infrastructure

#1016 Fixes #1004, get rid of old chart stuff
  src/forms/output/BenefitsLineGraph.js
  src/forms/output/StackedAreaGraph.js
  src/forms/output/StackedBarGraph.js
  src/forms/output/VerticalLine.js
  src/test/forms/output/BenefitsLines.test.js
  src/test/forms/output/ResourcesColumns.test.js
  src/test/forms/output/StackedResources.test.js
  src/test/forms/output/__snapshots__/BenefitsLineGraph.test.js.snap
  src/test/forms/output/__snapshots__/StackedAreaGraph.test.js.snap
  src/test/forms/output/__snapshots__/StackedBarGraph.test.js.snap
Labels: infrastructure

#1000 Dev utilities. Fixes #999
  package-lock.json
  package.json
  src/App.js
  src/containers/VisitPage.js
  src/dev/command-line-utils.js
Labels: feature, infrastructure

#1025 Cleans code style of '/src/components' through 'Surrounder`. #1018
  src/components/MainMenu.js
  src/components/PageLayout.js
  src/components/StepBar.js
  src/components/Surrounder.js
  src/containers/VisitPage.js
  src/test/components/StepBar.test.js
Labels: infrastructure

#1027 Cleans code style of '/src/data'. #1018
  src/data/federal/2017/SNAPData.js
  src/data/federal/federalPovertyGuidelines.js
  src/data/massachusetts/name-cores.js
  src/forms/output/zoom.js
Labels: infrastructure

#1028 Cleans code style of '/src/forms/output'. #1018
  src/forms/output/BenefitsLines.js
  src/forms/output/BenefitsTable.js
  src/forms/output/GraphHolder.js
  src/forms/output/ResourcesColumns.js
  src/forms/output/StackedResources.js
  src/forms/output/Summary.js
  src/forms/output/chartStringTransformers.js
  src/forms/output/zoom.js
  src/test/forms/output/__snapshots__/BenefitsTable.test.js.snap
Labels: infrastructure
