Repository codeforboston/cliff-effects, pull requests merged in 2018-10, with the labels that each got.

#808 Another, similar, option for buttons - only one button file
  src/containers/VisitPage.js
  src/forms/ButtonReset.js
  src/forms/FormPartsContainer.js
Labels: infrastructure

#813 Adds version numbers to Household section snippets - #752
  src/localization/en.js
  src/localization/vi.js
Labels: infrastructure

#814 Adds version numbers to Income section snippets - #752
  src/localization/en.js
  src/localization/vi.js
Labels: infrastructure

#815 Adds version numbers to Expenses section snippets, and vi - #752
  src/localization/en.js
  src/localization/vi.js
  src/test/forms/__snapshots__/CurrentExpenses.test.js.snap
Labels: infrastructure

#811 Adds some tab-ability and visual feedback - starts #816
  src/components/details.js
  src/forms/CurrentExpenses.js
  src/forms/Household.js
  src/forms/Predictions.js
  src/forms/inputs.js
  src/index.css
Labels: feature

#806 Implements 'Overview' (you can see it in the wiki too)
  OVERVIEW.md
  README.md
  package.json
Labels: feature

#820 Cleans out useless jsdoc comments for 'Household' section - #821
  src/forms/Household.js
Labels: feature, infrastructure

#819 Lints
  src/localization/vi.js
Labels: infrastructure

#827 Just the HUD off button (I do at least want that)
  src/components/dev/DevHud.js
  src/styles/dev.css
Labels: feature, infrastructure

#828 Fixes HUD checkbox broken (copy/paste typo)
  src/components/dev/DevHud.js
Labels: bug

#830 Adds size flexibility and scrollability to hud menu
  src/components/dev/DevHud.js
  src/styles/dev.css
Labels: feature, infrastructure

#835 Cleans docs a bit for formHelpers. Not comprehensive. #821
  src/forms/formHelpers.js
Labels: feature, infrastructure

#795 Shows result as plain text - fixes #771, fixes #764, fixes #763, starts #554
  src/forms/Predictions.js
  src/forms/output/BenefitText.js
  src/index.css
  src/localization/en.js
Labels: feature

#837 Cleans docs for snippet stuff - #821
  src/localization/all.js
  src/localization/contributors.js
  src/localization/inlineComponents.js
Labels: feature, infrastructure

#832 Cleans docs a bit for Expenses section. Not comprehensive. #821
  src/forms/CurrentExpenses.js
  src/forms/ExpensesOther.js
Labels: infrastructure

#833 Cleans docs a bit for Predictions section. Not comprehensive. #821
  src/forms/Predictions.js
Labels: infrastructure

#818 Cleans up docs for /components a bit - #821
  src/components/AboutContent.js
  src/components/CustomClient.js
  src/components/dev/DevHud.js
  src/components/renderIfTrue.js
Labels: feature, infrastructure

#843 Single tab and focus styles for home buttons. #842, fixes #841
  src/containers/HomePage.js
  src/index.css
Labels: bug

#834 Cleans docs a bit for cashflow + others. Not comprehensive. #821
  src/forms/FormPartsContainer.js
  src/forms/cashflow.js
  src/forms/inputs.js
Labels: feature, infrastructure

#836 Cleans docs a bit for calc outputs. Not comprehensive. #821
  src/forms/output/BenefitsTable.js
  src/forms/output/StackedAreaGraph.js
  src/forms/output/StackedBarGraph.js
  src/forms/output/VerticalLine.js
Labels: feature, infrastructure

#839 Turns result text summary into snippets - mentioned in #795
  src/forms/Predictions.js
  src/forms/output/Summary.js
  src/localization/en.js
Labels: feature, infrastructure

#831 Predictions warning modal (formerly Terms and Conditions modal)
  src/App.js
  src/components/prompts/PredictionsWarning.js
  src/containers/VisitPage.js
  src/index.css
  src/localization/en.js
Labels: feature

#822 Cleans up docs a bit for Income section. Not comprehensive. #821
  src/forms/CurrentIncome.js
Labels: feature, infrastructure

#829 Focus styles on the feedback form work, styles tweaked - #816
  src/components/prompts/FeedbackForm.js
  src/index.css
Labels: feature

#859 Adds outlines back into the home page buttons
  src/index.css
Labels: bug

#823 Cleans up docs a bit for Benefits section. Not comprehensive. #821
  src/forms/CurrentBenefits.js
Labels: feature, infrastructure

#864 Removes carats from deps. Fixes #856
  package-lock.json
  package.json
Labels: bug, infrastructure

#867 Switches fake to real message since it shows up sometimes.
  src/components/prompts/ReactRouterLeaveListener.js
Labels: bug

#871 A short one. Just lints.
  src/components/prompts/PredictionsWarning.js
  src/containers/VisitPage.js
Labels: infrastructure

#876 Header structural adjustments
  src/components/Header.js
  src/components/MainMenu.js
  src/index.css
Labels: infrastructure

#874 Adds github as explicit header menu item. Fixes #873.
  src/components/MainMenu.js
  src/localization/en.js
Labels: feature

#879 Shallow cleaning of section8 documentation
  src/programs/massachusetts/section8.js
Labels: feature, infrastructure

#877 Updates status of the project
  README.md
Labels: feature, infrastructure

#869 Fixes #868 reset text gone. Also messes with wording T_T
  src/components/prompts/FeedbackAnytime.js
  src/components/prompts/FeedbackPrompt.js
  src/containers/VisitPage.js
  src/forms/ButtonReset.js
  src/test/components/prompts/__snapshots__/FeedbackPrompt.test.js.snap
Labels: bug

#886 Fixes #885 fix tests failing because new snippets
  src/test/components/Header.test.js
  src/test/components/MainMenu.test.js
Labels: bug

#878 Updates to reflect status of the project
  src/localization/en.js
  src/localization/inlineComponents.js
Labels: feature

#888 Abstract calcing so each state can have its own. Fixes #887
  src/programs/allBenefitOps.js
  src/programs/allBenefitOrders.js
  src/programs/applyAndPushBenefits.js
  src/programs/massachusetts/benefitOps.js
  src/programs/massachusetts/benefitOrder.js
Labels: infrastructure

#884 Improve readability of SNAP calcs
  src/programs/federal/snap.js
  src/test/programs/federal/snap/unit.test.js
  src/test/utils/getMembers.test.js
  src/utils/getMembers.js
Labels: help wanted, infrastructure

#872 More robust styles and structure for left-fixed buttons
  src/components/prompts/FeedbackAnytime.js
  src/components/prompts/ResetAnytime.js
  src/containers/VisitPage.js
  src/index.css
Labels: infrastructure

#889 Tests ButtonReset component #446
  src/test/components/ButtonReset.test.js
Labels: testing

#894 Reuses 'ResetButton' for all 'New Client' buttons. Fixes #893
  src/components/prompts/ResetAnytime.js
  src/containers/VisitPage.js
  src/forms/ButtonReset.js
  src/forms/inputs.js
  src/index.css
  src/test/forms/inputs/BigButton.test.js
Labels: infrastructure

#898 Fixes #895 replace renderIfTrue type stuff with our ternary format
  src/App.js
  src/components/prompts/FeedbackForm.js
  src/components/renderIfTrue.js
  src/forms/ExpensesOther.js
  src/test/components/renderIfTrue.test.js
Labels: infrastructure

#903 Fixes #851, duplicate keys, either temporarily or permanently
  src/forms/output/Summary.js
Labels: bug, infrastructure

#891 Hover Contrast. #816 and fixes #852
  src/components/MainMenu.js
  src/index.css
Labels: feature

#906 Changes var name to reflect purpose (not terms of service)
  src/App.js
  src/components/prompts/PredictionsWarning.js
  src/containers/VisitPage.js
Labels: infrastructure

#904 Add linting pre-commit hook via husky and lint-staged packages. Fixes #897
  package-lock.json
  package.json
Labels: infrastructure

#925 Lints
  src/App.js
  src/components/MainMenu.js
  src/components/prompts/FeedbackForm.js
  src/containers/VisitPage.js
  src/forms/ExpensesOther.js
  src/forms/FormPartsContainer.js
  src/test/components/ButtonReset.test.js
  src/test/forms/cashflow/MonthlyCashFlowRow.test.js
  src/test/forms/folderHelpers/AttentionArrow.test.js
  src/test/forms/inputs/BigButton.test.js
  src/test/forms/output/BenefitsLineGraph.test.js
  src/test/forms/output/StackedAreaGraph.test.js
Labels: infrastructure

#926 Fixes #914, `onClick` not getting passed to `BigButton`
  src/forms/inputs.js
  src/test/forms/inputs/BigButton.test.js
Labels: bug, infrastructure

#924 Puts errors above the invalid question answer. Fixes #909
  src/components/Surrounder.js
  src/containers/VisitPage.js
  src/forms/cashflow.js
  src/forms/formHelpers.js
  src/forms/inputs.js
  src/forms/rentFields.js
  src/index.css
  src/test/components/__snapshots__/Surrounder.test.js.snap
  src/test/forms/cashflow/CashFlowContainer.test.js
  src/test/forms/cashflow/__snapshots__/CashFlowContainer.test.js.snap
  src/test/forms/cashflow/__snapshots__/CashFlowInputsRow.test.js.snap
  src/test/forms/folderHelpers/InvalidMessage.test.js
Labels: feature

#930 Fixes #928, remove lint-staged till it's shown to be working
  package-lock.json
  package.json
Labels: infrastructure

#918 More validation in `stringToNumber()` #917
  src/test/utils/valueFixers.test.js
  src/utils/validators.js
  src/utils/valueFixers.js
Labels: infrastructure

#922 Fixes #545, Form routes
  src/App.js
  src/components/StepBar.js
  src/components/prompts/ReactRouterLeaveListener.js
  src/constants.js
  src/containers/VisitPage.js
  src/test/components/StepBar.test.js
Labels: feature
